// Generated by CoffeeScript 1.10.0
(function() {
  var Clean_up, DataTypes, Sequelize, insert_group_name, sequelize;

  Sequelize = require('sequelize');

  sequelize = new Sequelize('infbot_db', 'infinith4', 'infinith4');

  DataTypes = require('sequelize/lib/data-types');

  Clean_up = sequelize.define('clean_up', {
    id: {
      type: DataTypes.INTEGER(11),
      allowNull: false,
      primaryKey: true,
      autoIncrement: true
    },
    group_name: {
      type: DataTypes.TEXT,
      allowNull: false
    }
  }, {
    timestamps: true,
    tableName: 'clean_up'
  });

  insert_group_name = "";

  Clean_up.findOne({
    order: 'createdAt DESC'
  }).then(function(record) {
    console.log(record.get({
      plane: true
    }));
    console.log(record.group_name);
    console.log("record.group_name");
    switch (record.group_name) {
      case "A":
        insert_group_name = "B";
        break;
      case "B":
        insert_group_name = "A";
    }
    console.log("insert_group_name");
    console.log(insert_group_name);
    if (insert_group_name !== "") {
      return sequelize.sync().then(function() {
        return Clean_up.create({
          group_name: insert_group_name
        });
      }).then(function(result) {
        return console.log(result.get({
          plain: true
        }));
      });
    }
  });

}).call(this);
