// // Generated by CoffeeScript 1.10.0
// (function() {
//   var DataTypes, Sequelize, Users, sequelize;
//
//   Sequelize = require('sequelize');
//
//   sequelize = new Sequelize('infbot_db', 'infinith4', 'infinith4');
//
//   DataTypes = require('sequelize/lib/data-types');
//
//   Users = sequelize.define('users', {
//     uid: {
//       type: DataTypes.INTEGER(11),
//       allowNull: false,
//       primaryKey: true,
//       autoIncrement: true
//     },
//     name: {
//       type: DataTypes.TEXT,
//       allowNull: false
//     },
//     password: {
//       type: DataTypes.TEXT,
//       allowNull: true
//     }
//   }, {
//     timestamps: true,
//     tableName: 'users',
//     timezone: '+09:00'
//   });
//
//   sequelize.sync({
//     force: true
//   }).then(function() {
//     return Users.create({
//       name: 'infinith4',
//       password: 'infinith4'
//     });
//   }).then(function(jane) {
//     console.log(jane.get({
//       plain: true
//     }));
//   });
//
//   Users.findAll().then(function(person) {
//     var i, item, len, results;
//     results = [];
//     for (i = 0, len = person.length; i < len; i++) {
//       item = person[i];
//       results.push(console.log(item.uid));
//     }
//     return results;
//   });
//
// }).call(this);
